### ISSUE TITLE
teeapp自定义组件，是否考虑支持Java类型的应用

### ISSUE THREAD

**Issue by bronzeMe** [secretflow/teeapps#12]
目前的teeapps组件只支持python 代码，后期是否考虑支持其他语言的应用，比如运行Java代码、Go代码等
比如Java SPARK程序处理大数据计算

**Comment by zhongtianq** [comment]
如果进行二次开发的话只需按需求修改std::string GenCmd(const std::string& component_name, const std::string& plat)这个函数即可。

**Comment by bronzeMe** [comment]
顺便讨论一个问题，WaitAndReadOutput，https://github.com/secretflow/teeapps/blob/main/teeapps/framework/subprocess.cc#L83 
目前的实现是同步阻塞的方式，子进程结束后才返回子进程的Stdout stderr，这里如果采用异步的方式是不是会改进一下性能
最近测试发现一个现象，同一个python代码（比如PSI，两个CSV主键ID求交）在没有集成到teeapps时，直接运行可能要2分钟，但把这个Python代码集成到TEEapp作为一个组件后，运行时间会到7分钟（会增加一定的倍数），在SIM模式下测试的结果。
观察了一下加解密以及文件拷贝其实很快不会耗费太多时间，
所以推测大概率是同样的Python代码集成为一个teeapps组件后，suprocess的方式运行导致了性能下降，但是SIM模式下应该直接运行和subprocess运行理论上差别不应该太大，这边推测很可能是WaitAndReadOutput这里引入的

**Comment by zhongtianq** [comment]
> 顺便讨论一个问题，WaitAndReadOutput，https://github.com/secretflow/teeapps/blob/main/teeapps/framework/subprocess.cc#L83 目前的实现是同步阻塞的方式，子进程结束后才返回子进程的Stdout stderr，这里如果采用异步的方式是不是会改进一下性能 最近测试发现一个现象，同一个python代码（比如PSI，两个CSV主键ID求交）在没有集成到teeapps时，直接运行可能要2分钟，但把这个Python代码集成到TEEapp作为一个组件后，运行时间会到7分钟（会增加一定的倍数），在SIM模式下测试的结果。 观察了一下加解密以及文件拷贝其实很快不会耗费太多时间， 所以推测大概率是同样的Python代码集成为一个teeapps组件后，suprocess的方式运行导致了性能下降，但是SIM模式下应该直接运行和subprocess运行理论上差别不应该太大，这边推测很可能是WaitAndReadOutput这里引入的

这个问题建议在组件中日志加上时间戳，看看耗时具体是在什么步骤中产生，是求交中还是在结果输出中。

**Comment by bronzeMe** [comment]
我的意思是，同样的一个python代码，比如那PSI.py举例，

- 直接python psi.py 耗时2分钟

- ./main --plat=sim --enable_console_logger=true --enable_capsule_tls=false --entry_task_config_path=/host/integration_test/psi_task.json 耗时7分钟，还是同一样的psi.py逻辑没变，
- 加解密其实耗时很小的

**Comment by zhongtianq** [comment]
可以提供一下我说的对应时间吗？组件里面的运行时间，打一些日志。  可以对比出来两者的区别。
