### ISSUE TITLE
sim模式下PSI算法求交结果错误

### ISSUE THREAD

**Issue by PrimumMobile** [secretflow/teeapps#16]
https://github.com/secretflow/teeapps/blob/main/teeapps/biz/common/common.py#L289
file_num不同，会导致相同数据映射到不同的file_index，从而导致交集计算错误。

**Comment by zhongtianq** [comment]
感谢反馈，这个问题会在6.15发版修复（待发布）
简单来说是需要将求交两边数据分桶数设置成相同。

**Comment by PrimumMobile** [comment]
> 感谢反馈，这个问题会在6.15发版修复（待发布） 简单来说是需要将求交两边数据分桶数设置成相同。

ok，还有一个问题，如果两方的数据集里面有相同名称的列，在gen_output_schema的时候会报错，比如两方都有名为y的列，在求交的时候会被修改为y_x和y_y，gen_output_schema函数schema参数里面列名貌似还是y，会报一个y_x not found in schema的异常，这个你们发现没有？

**Comment by zhongtianq** [comment]
> > 感谢反馈，这个问题会在6.15发版修复（待发布） 简单来说是需要将求交两边数据分桶数设置成相同。
> 
> ok，还有一个问题，如果两方的数据集里面有相同名称的列，在gen_output_schema的时候会报错，比如两方都有名为y的列，在求交的时候会被修改为y_x和y_y，gen_output_schema函数schema参数里面列名貌似还是y，会报一个y_x not found in schema的异常，这个你们发现没有？

我理解一下，这个问题是指两方有一列同名的y，但是没有把同名的y列作为求交列。pandas的merge会将两列附加一个后缀都append到结果中。

对于这样的特殊情形，我们考虑后还是建议将原始表的列名做一下修改。因为这会产生一些特质化的需求，我们不希望将这些需求写入到组件中。
