### ISSUE TITLE
隐私求交组件无法引用上一个组件计算的结果

### ISSUE THREAD

**Issue by bronzeMe** [secretflow/teeapps#17]
<img width="208" alt="image" src="https://github.com/secretflow/teeapps/assets/11402109/4d4d0b5d-7bcf-4a93-8f3f-e84eaa6e2664">
如上图所示，

问题1：目前隐私求交组件的输入只能是样本表，这样主键列表才能展示出可选的主键名称，如果输入是上一个组件的结果，则无法展示可选的主键名称
问题2：如果隐私求交组件是上一个组件的输入，它会认为输入的是两个一样的样本表
<img width="402" alt="image" src="https://github.com/secretflow/teeapps/assets/11402109/fc9f71c4-66c3-423f-bbc5-a6a3495d53b5">

**Comment by zhongtianq** [comment]
这个看起来都是secretpad的问题，麻烦转移到那个repo下面吧。

**Comment by aokaokd** [comment]
你用的所有组件都有什么，辛苦截图一下你的画布

**Comment by bronzeMe** [comment]
> 你用的所有组件都有什么，辛苦截图一下你的画布

https://github.com/secretflow/secretpad/issues/78 参考这个
