### ISSUE TITLE
更新了teeapps后需要重头开始执行所有的任务流，使用体验不太友好

### ISSUE THREAD

**Issue by bronzeMe** [secretflow/teeapps#21]
### Issue Type

Feature Request

### Source

source

### Capsule Manager Version

0.3.0b0

### Capsule Manager SDK Version

0.3.0b0

### Tee Apps Version

0.3.0b0

### OS Platform and Distribution

Ubuntu22.04

### Python version

3.8.10

### What happend and What you expected to happen.

```shell
teeapps更新后，重新注册策略（数据ID不变，对应的mrenclave更新为新的TEEAPP），这个时候要使用新teeapps需要重新重头开始执行，比如上层有几个组件已经执行完了，此时更新了teeapps，上层的计算也需要重头重新执行（需要重头开始执行所有的任务流）
从使用体验角度，不用重头开始执行会比较好，有什么优化方式么
```

### Reproduction code to reproduce the issue.

```shell
历史任务流中，升级了teeapps，mrenclave改变了，需要重头开始执行所有的任务流
```

**Comment by zimu-yuxi** [comment]
@bronzeMe 
hi，是可视化页面跑的还是黑屏跑的呢？

**Comment by bronzeMe** [comment]
可视化界面跑的

**Comment by zimu-yuxi** [comment]
页面上有从当前节点开始运行的按钮，看下是否符合你的预期呢？

**Comment by bronzeMe** [comment]
问题是这样的：比如T0时刻，训练流上有A->B-C 三个组件（串行，并且是依赖上一个组件的结果），T1时刻，teeapps 更新了度量值，此时也更新了CM里的策略， T2时刻，点击运行C组件时会出现无法运行，需要把A->B-C从A开始重新运行一遍
从使用体验角度：应该在T2时刻，teeapps更新了， 但不需要重头执行所有的组件，单独运行C就可以
不知道是否明白我说的意思

**Comment by wenkesong-li** [comment]
您好，该问题已记录，考虑在后续版本中迭代优化。感谢您的反馈~

**Comment by bronzeMe** [comment]
您好，如果要优化，这个问题需要哪些模块进行优化呢，CM策略管理进行修改么？
