### ISSUE TITLE
Is it safe to temporarily save the decrypted files on the disk ?

### ISSUE THREAD

**Issue by gxcuit** [secretflow/teeapps#24]
Hi,  我在使用 Trustedflow 0.3.0b0， `secretflow/teeapps-csv-ubuntu22.04:latest` 这个版本

我有一个问题：carol 作为TEE的执行方，他可以访问解密后的数据，这个是否有安全风险？ Trustedflow里的安全模型是什么？
----
 
Please kindly refer to the following code:

https://github.com/secretflow/teeapps/blob/0b5530c31d196a75a8634efb84465842ccaa3550/teeapps/framework/app.cc#L255

It seems that carol decrypts files and stores them temporarily in the path `/home/teeapp/task/input1.dat`.

Even if the decrypted files are deleted after running the task. It may be possible for Carol to "steal" the input files from Alice/Bob.  Would it make more sense to store the files in memory, just like the decryption key?

**Comment by zimu-yuxi** [comment]
hi，please refer to [here](https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.0b0/architecture/principle#trustedflow)

**Comment by gxcuit** [comment]
> hi，please refer to [here](https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.0b0/architecture/principle#trustedflow)

我想知道，carol， 其实是能获取到alice.csv 以及bob.csv的。 有安全问题吗

**Comment by zimu-yuxi** [comment]
> > hi，please refer to [here](https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.0b0/architecture/principle#trustedflow)
> 
> 我想知道，carol， 其实是能获取到alice.csv 以及bob.csv的。 有安全问题吗

1.并不限定TEE机器必须是第三方（carol）提供，可以是alice或者bob自身，官网以carol提供TEE机器为例是为了方便进行说明
2.如果你有第三方carol提供TEE机器，默认carol是可信的，依赖它的TEE硬件，然后会做远程认证和相关授权策略，保护数据的机密性、完整性和可用性

可以参考下[官网说明](https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.0b0)

**Comment by zhongtianq** [comment]
首先，解密过程仅在tee中发生。carol只是tee的搭建方，他并不能任意地在tee中执行命令。
其次，对于sgx模式，occlum是有自身的加密文件系统的，解密后的文件并不能直接被看到。  对于TDX和CSV的场景，在VM启动的时候可以使用磁盘加密的功能，使得VM中的文件也无法被明文看到。
