### ISSUE TITLE
关于trustedflow开发者新添加组件时，构建Teeapps镜像失败的问题

### ISSUE THREAD

**Issue by Lucas-16** [secretflow/teeapps#25]
### Issue Type

Bug

### Source

binary

### Capsule Manager Version

0.1.0b

### Capsule Manager SDK Version

0.1.0b

### Tee Apps Version

0.1.0b

### OS Platform and Distribution

Ubuntu22.04

### Python version

3.8.13

### Bazel version

6.2.1

### What happend and What you expected to happen.

```shell
执行 bash build.sh -p sim -v 0.1.0 失败，看日志貌似时bazel的问题？但bazel已安装，想请问这个问题应该如何调试？
```

### Reproduction code to reproduce the issue.

```shell
Step 8/24 : RUN bash ./scripts/build_sim.sh
 ---> Running in f19663ed9b77
2024/07/11 11:12:43 Downloading https://releases.bazel.build/6.2.1/release/bazel-6.2.1-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/bazelbuild/apple_support/releases/download/0.11.0/apple_support.0.11.0.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/upb/archive/e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/bazelbuild/rules_apple/releases/download/0.32.0/rules_apple.0.32.0.tar.gz failed: class java.io.IOException connect timed out
Loading: 
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/envoyproxy/data-plane-api/archive/bf6154e482bbd5e6f64032993206e66b6116f2bd.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/googleapis/googleapis/archive/2f9af297c84c55c8b871ba4495e01ade42476c92.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/protobuf/archive/24487dd1045c7f3d64a21f38a3f0c06cc4cf2edb.tar.gz failed: class java.io.IOException connect timed out
Loading: 
Loading: 
DEBUG: /home/admin/dev/target/external/rules_python/python/repositories.bzl:32:10: py_repositories is a no-op and is deprecated. You can remove this from your WORKSPACE file
Loading: 
Loading: 
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: teeapps/biz/lr ... (130 packages)
ERROR: /home/admin/dev/teeapps/component/target/external/build_bazel_rules_apple/test/testdata/binaries/BUILD:29:1: name 'apple_static_library' is not defined
INFO: Repository bazel_skylib instantiated at:
  /home/admin/dev/WORKSPACE:27:10: in <toplevel>
  /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:313:21: in grpc_deps
Repository rule http_archive defined at:
  /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Skipping '//teeapps/...': error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/com_github_grpc_grpc/third_party/upb/upbc': cannot load '//bazel:upb_proto_library.bzl': no such file
WARNING: Target pattern parsing failed.
ERROR: error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/com_github_grpc_grpc/third_party/upb/upbc': cannot load '//bazel:upb_proto_library.bzl': no such file
INFO: Elapsed time: 81.811s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (44 packages loaded)
```

**Comment by Lucas-16** [comment]
不好意思，上述错误好像是网络问题，但在使用外网后，依然未执行成功，报错如下（貌似好像是bazel的问题，但不知如何解决）：
 > [builder 8/8] RUN bash ./scripts/build_sim.sh:                                                                                                                                          
0.228 2024/07/12 02:50:20 Downloading https://releases.bazel.build/6.2.1/release/bazel-6.2.1-linux-x86_64...                                                                               
13.35 Extracting Bazel installation...                                                                                                                                                     
15.19 Starting local Bazel server and connecting to it...                                                                                                                                  
17.46 Loading:                                                                                                                                                                             
18.46 Loading: 
20.22 Loading: 
21.23 Loading: 
22.40 Loading: 
23.47 Loading: 
24.47 Loading: 
25.47 Loading: 
26.47 Loading: 
27.49 Loading: 
29.33 Loading: 
30.46 Loading: 
31.48 Loading: 
32.04 DEBUG: /home/admin/dev/target/external/rules_python/python/repositories.bzl:32:10: py_repositories is a no-op and is deprecated. You can remove this from your WORKSPACE file
32.48 Loading: 
34.42 Loading: 
34.96 Loading: 
34.97 Loading: 0 packages loaded
36.53 Loading: 0 packages loaded
36.53     currently loading: teeapps/component/target/external/com_google_googleapis/google/spanner ... (11 packages)
36.72 ERROR: /home/admin/dev/teeapps/component/target/external/build_bazel_rules_apple/test/testdata/binaries/BUILD:29:1: name 'apple_static_library' is not defined
37.15 INFO: Repository bazel_skylib instantiated at:
37.15   /home/admin/dev/WORKSPACE:27:10: in <toplevel>
37.15   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:313:21: in grpc_deps
37.15 Repository rule http_archive defined at:
37.15   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
37.20 INFO: Repository rules_cc instantiated at:
37.20   /home/admin/dev/WORKSPACE:27:10: in <toplevel>
37.20   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:243:21: in grpc_deps
37.20 Repository rule http_archive defined at:
37.20   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
38.20 Loading: 52 packages loaded
38.20     currently loading: teeapps/component/target/external/com_google_googleapis/google/logging/type ... (193 packages)
38.20 INFO: Repository rules_proto instantiated at:
38.20   /home/admin/dev/WORKSPACE:31:16: in <toplevel>
38.20   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:49:18: in grpc_extra_deps
38.20   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:73:24: in protobuf_deps
38.20   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:19:17: in _github_archive
38.20 Repository rule http_archive defined at:
38.20   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
38.36 INFO: Repository rules_java instantiated at:
38.36   /home/admin/dev/WORKSPACE:31:16: in <toplevel>
38.36   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:49:18: in grpc_extra_deps
38.36   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:65:24: in protobuf_deps
38.36   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:19:17: in _github_archive
38.36 Repository rule http_archive defined at:
38.36   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
38.39 ERROR: Skipping '//teeapps/...': error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/rules_proto_grpc/csharp': cannot load '//:defs.bzl': no such file
38.39 WARNING: Target pattern parsing failed.
38.40 ERROR: error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/rules_proto_grpc/csharp': cannot load '//:defs.bzl': no such file
38.45 INFO: Elapsed time: 25.034s
38.45 INFO: 0 processes.
38.45 FAILED: Build did NOT complete successfully (52 packages loaded)
------
Dockerfile:25
--------------------
  23 |     COPY scripts/build_sim.sh ./scripts/build_sim.sh
  24 |     
  25 | >>> RUN bash ./scripts/build_sim.sh
  26 |     
  27 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c bash ./scripts/build_sim.sh" did not complete successfully: exit code: 1

**Comment by wangzul** [comment]
方便说一下，构建镜像的源码的版本吗。

**Comment by Lucas-16** [comment]
> 方便说一下，构建镜像的源码的版本吗。
直接 git clone https://github.com/secretflow/teeapps.git 拉下来的，我看目前teeapps这个repo里只有一个版本吧？

**Comment by Lucas-16** [comment]
> 方便说一下，构建镜像的源码的版本吗。

应该是0.3.0b0

**Comment by Lucas-16** [comment]
又重新执行了下 bash build.sh -p sim -v 0.2.0，报的错又不一样了...以下是报错信息
 > [builder 8/8] RUN bash ./scripts/build_sim.sh:                                                                                                                                          
0.232 2024/07/12 06:58:02 Downloading https://releases.bazel.build/6.2.1/release/bazel-6.2.1-linux-x86_64...                                                                               
12.85 Extracting Bazel installation...                                                                                                                                                     
15.48 Starting local Bazel server and connecting to it...                                                                                                                                  
17.57 Loading:                                                                                                                                                                             
18.58 Loading: 
20.28 Loading: 
21.35 Loading: 
22.57 Loading: 
23.58 Loading: 
24.65 Loading: 
26.08 Loading: 
27.10 Loading: 
28.15 Loading: 
29.35 Loading: 
30.58 Loading: 
31.78 Loading: 
32.82 Loading: 
33.83 Loading: 
34.98 Loading: 
35.12 DEBUG: /home/admin/dev/target/external/rules_python/python/repositories.bzl:32:10: py_repositories is a no-op and is deprecated. You can remove this from your WORKSPACE file
36.08 Loading: 
37.58 Loading: 
38.87 Loading: 
38.87 Loading: 0 packages loaded
40.37 Loading: 0 packages loaded
40.37     currently loading: teeapps/component/target/external/io_bazel_rules_go/tests/legacy/examples/cgo ... (3 packages)
41.08 INFO: Repository rules_cc instantiated at:
41.08   /home/admin/dev/WORKSPACE:27:10: in <toplevel>
41.08   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:243:21: in grpc_deps
41.08 Repository rule http_archive defined at:
41.08   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
41.08 INFO: Repository bazel_skylib instantiated at:
41.08   /home/admin/dev/WORKSPACE:27:10: in <toplevel>
41.08   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:313:21: in grpc_deps
41.08 Repository rule http_archive defined at:
41.08   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
41.42 Loading: 17 packages loaded
41.42     currently loading: teeapps/component/target/external/io_bazel_rules_go/tests/legacy/examples/cgo ... (289 packages)
41.42 INFO: Repository rules_proto instantiated at:
41.42   /home/admin/dev/WORKSPACE:31:16: in <toplevel>
41.42   /home/admin/dev/target/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:49:18: in grpc_extra_deps
41.42   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:73:24: in protobuf_deps
41.42   /home/admin/dev/target/external/com_google_protobuf/protobuf_deps.bzl:19:17: in _github_archive
41.42 Repository rule http_archive defined at:
41.42   /home/admin/dev/target/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
41.47 ERROR: Skipping '//teeapps/...': error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/upb/upb/fuzz': Unable to find package for @rules_fuzzing//fuzzing:cc_defs.bzl: The repository '@rules_fuzzing' could not be resolved: Repository '@rules_fuzzing' is not defined.
41.47 WARNING: Target pattern parsing failed.
41.47 ERROR: error loading package under directory 'teeapps': error loading package 'teeapps/component/target/external/upb/upb/fuzz': Unable to find package for @rules_fuzzing//fuzzing:cc_defs.bzl: The repository '@rules_fuzzing' could not be resolved: Repository '@rules_fuzzing' is not defined.
41.51 INFO: Elapsed time: 28.610s
41.51 INFO: 0 processes.
41.51 FAILED: Build did NOT complete successfully (17 packages loaded)
![屏幕截图 2024-07-12 145953](https://github.com/user-attachments/assets/83251eac-7e4a-4ed3-88f8-0a913effaabc)

**Comment by wangzul** [comment]
您的问题我已经了解了，现在需要时间去复现排查。

**Comment by wangzul** [comment]
_github_archive(
            name = "upb",
            repo = "https://github.com/protocolbuffers/upb",
            commit = "333722e94b35c26b9eb48bd7e471235374ab3737",
            sha256 = "f973aefa29d4191aad76cd1ba74ee3be4d2161b6c95d73c137f82560983912c6",
        )
这个是代码中upb的配置信息，可以尝试一下能否正常访问这个repo。
如果可以正常访问可以通过以下方式再次尝试
#创建容器
 docker run -dt --name test secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest
docker exec -it test bash
git clone  https://github.com/secretflow/teeapps.git && cd teeapps/
 bazel --output_base=target build -c opt --copt=-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG //teeapps/...
如果失败了ls target/external/upb/upb/fuzz  查看是否存在，如果不存在手动拉取repo放入target/external后重新执行编译命令

**Comment by Lucas-16** [comment]
> ```
>     _github_archive(
>         name = "upb",
>         repo = "https://github.com/protocolbuffers/upb",
>         commit = "333722e94b35c26b9eb48bd7e471235374ab3737",
>         sha256 = "f973aefa29d4191aad76cd1ba74ee3be4d2161b6c95d73c137f82560983912c6",
>     )
> ```
> 
> 这个是代码中upb的配置信息，可以尝试一下能否正常访问这个repo。 如果可以正常访问可以通过以下方式再次尝试 #创建容器 docker run -dt --name test secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest docker exec -it test bash git clone https://github.com/secretflow/teeapps.git && cd teeapps/ bazel --output_base=target build -c opt --copt=-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG //teeapps/... 如果失败了ls target/external/upb/upb/fuzz 查看是否存在，如果不存在手动拉取repo放入target/external后重新执行编译命令

![Uploading 屏幕截图 2024-07-16 164333.jpg…]()
按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？

**Comment by Lucas-16** [comment]
> ```
>     _github_archive(
>         name = "upb",
>         repo = "https://github.com/protocolbuffers/upb",
>         commit = "333722e94b35c26b9eb48bd7e471235374ab3737",
>         sha256 = "f973aefa29d4191aad76cd1ba74ee3be4d2161b6c95d73c137f82560983912c6",
>     )
> ```
> 
> 这个是代码中upb的配置信息，可以尝试一下能否正常访问这个repo。 如果可以正常访问可以通过以下方式再次尝试 #创建容器 docker run -dt --name test secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest docker exec -it test bash git clone https://github.com/secretflow/teeapps.git && cd teeapps/ bazel --output_base=target build -c opt --copt=-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG //teeapps/... 如果失败了ls target/external/upb/upb/fuzz 查看是否存在，如果不存在手动拉取repo放入target/external后重新执行编译命令

按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？
![Uploading 屏幕截图 2024-07-16 164333.jpg…]()

**Comment by Lucas-16** [comment]
按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？
![屏幕截图 2024-07-16 164333](https://github.com/user-attachments/assets/7eb9b3f2-fed9-4339-ade7-6a6ac97dbaf8)

**Comment by wangzul** [comment]
> 按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？ ![屏幕截图 2024-07-16 164333](https://private-user-images.githubusercontent.com/45684182/349011896-7eb9b3f2-fed9-4339-ade7-6a6ac97dbaf8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjEyNTMsIm5iZiI6MTcyMTEyMDk1MywicGF0aCI6Ii80NTY4NDE4Mi8zNDkwMTE4OTYtN2ViOWIzZjItZmVkOS00MzM5LWFkZTctNmE2YWM5N2RiYWY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5MDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWM3NDM0MTM4Y2M1OGQzYThiMWQ2OWY0MWI1NmZhMzA4NTIyMzM5NGEzNzEyY2M2NTM4MjQyZjU0NTJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4CE1TXg83hjHjKXCkGOYv663aPY7vptvWC4GT6retc)

第一步 scripts/build_sim.sh移除bazel --out.. 编译命令

第二步 保存编译通过的镜像如
docker run -dt --name test [secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest](http://secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest)
最终编译完毕后
获取公共目录pwd 留存
更新镜像docker commit test my/trustedflow-dev-ubuntu22.04:latest
第三步 deployment/sim/Dockerfile 
FROM my/trustedflow-dev-ubuntu22.04:latest as builder

WORKDIR [刚刚上方pwd的地址也就是最终执行编译命令的路径]

COPY scripts/build_sim.sh ./scripts/build_sim.sh

RUN bash ./scripts/build_sim.sh


FROM ubuntu:22.04

下方不做改动

**Comment by Lucas-16** [comment]
> > 按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？ ![屏幕截图 2024-07-16 164333](https://private-user-images.githubusercontent.com/45684182/349011896-7eb9b3f2-fed9-4339-ade7-6a6ac97dbaf8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjEyNTMsIm5iZiI6MTcyMTEyMDk1MywicGF0aCI6Ii80NTY4NDE4Mi8zNDkwMTE4OTYtN2ViOWIzZjItZmVkOS00MzM5LWFkZTctNmE2YWM5N2RiYWY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5MDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWM3NDM0MTM4Y2M1OGQzYThiMWQ2OWY0MWI1NmZhMzA4NTIyMzM5NGEzNzEyY2M2NTM4MjQyZjU0NTJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4CE1TXg83hjHjKXCkGOYv663aPY7vptvWC4GT6retc)
> 
> 第一步 scripts/build_sim.sh移除bazel --out.. 编译命令
> 
> 第二步 保存编译通过的镜像如 docker run -dt --name test [secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest](http://secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest) 最终编译完毕后 获取公共目录pwd 留存 更新镜像docker commit test my/trustedflow-dev-ubuntu22.04:latest 第三步 deployment/sim/Dockerfile FROM my/trustedflow-dev-ubuntu22.04:latest as builder
> 
> WORKDIR [刚刚上方pwd的地址也就是最终执行编译命令的路径]
> 
> COPY scripts/build_sim.sh ./scripts/build_sim.sh
> 
> RUN bash ./scripts/build_sim.sh
> 
> FROM ubuntu:22.04
> 
> 下方不做改动
老师您好，第一步和第二步执行完毕后不是创建了一个新的镜像嘛，那第三步是还需要重新进镜像里操作吗？修改Dockerfile后后续还需要怎么操作呀？感觉这里目标最终是应该创建一个替换原有trustedflow的镜像吧？

**Comment by zimu-yuxi** [comment]
编译通过之后可以使用build.sh去做镜像打包

**Comment by wangzul** [comment]
> > > 按照您的方法，将添加了我自定义的组件后的代码成功编译了，编译成功的话，这个镜像是不是就可以和官方教程中用build.sh那种方式构建的镜像一样使用呀？？ ![屏幕截图 2024-07-16 164333](https://private-user-images.githubusercontent.com/45684182/349011896-7eb9b3f2-fed9-4339-ade7-6a6ac97dbaf8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjEyNTMsIm5iZiI6MTcyMTEyMDk1MywicGF0aCI6Ii80NTY4NDE4Mi8zNDkwMTE4OTYtN2ViOWIzZjItZmVkOS00MzM5LWFkZTctNmE2YWM5N2RiYWY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5MDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWM3NDM0MTM4Y2M1OGQzYThiMWQ2OWY0MWI1NmZhMzA4NTIyMzM5NGEzNzEyY2M2NTM4MjQyZjU0NTJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4CE1TXg83hjHjKXCkGOYv663aPY7vptvWC4GT6retc)
> > 
> > 
> > 第一步 scripts/build_sim.sh移除bazel --out.. 编译命令
> > 第二步 保存编译通过的镜像如 docker run -dt --name test [secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest](http://secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/trustedflow-dev-ubuntu22.04:latest) 最终编译完毕后 获取公共目录pwd 留存 更新镜像docker commit test my/trustedflow-dev-ubuntu22.04:latest 第三步 deployment/sim/Dockerfile FROM my/trustedflow-dev-ubuntu22.04:latest as builder
> > WORKDIR [刚刚上方pwd的地址也就是最终执行编译命令的路径]
> > COPY scripts/build_sim.sh ./scripts/build_sim.sh
> > RUN bash ./scripts/build_sim.sh
> > FROM ubuntu:22.04
> > 下方不做改动
> > 老师您好，第一步和第二步执行完毕后不是创建了一个新的镜像嘛，那第三步是还需要重新进镜像里操作吗？修改Dockerfile后后续还需要怎么操作呀？感觉这里目标最终是应该创建一个替换原有trustedflow的镜像吧？

第一 二步是会创建一个新镜像
第三步调整调整dockerfile是考虑到你那边无法通过原始的trustedflow dockerfile进行编译，所以要替换原有trustedflow的镜像，这样调整过后就可以通过bash build.sh -p sim -v 0.1.0 进行构建了  
请注意-v 0.1.0  这个版本现在是你git clone -b 0.x.0b0 来控制

**Comment by Lucas-16** [comment]
新增添组件已经成功编译，构建了新的镜像。还想再请问下后续新组件应该如何使用呀？官方的trustedflow上手教程中给出的几个例子都在/host/integration_test有相应的json文件，但是自定义的组件却没有相对应的json，这个json文件是需要自己编写还是用什么方式获得？

**Comment by wangzul** [comment]
> 新增添组件已经成功编译，构建了新的镜像。还想再请问下后续新组件应该如何使用呀？官方的trustedflow上手教程中给出的几个例子都在/host/integration_test有相应的json文件，但是自定义的组件却没有相对应的json，这个json文件是需要自己编写还是用什么方式获得？

是需要自己编写对应的配置文件，可以参考文档https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.0b0/quick_start/step4#id7
