### ISSUE TITLE
light BGM组件的bug

### ISSUE THREAD

**Issue by 1853582** [secretflow/teeapps#26]
### Issue Type

Bug

### Source

binary

### Capsule Manager Version

0.3.0b0

### Capsule Manager SDK Version

0.3.0b0

### Tee Apps Version

0.3.0b0

### OS Platform and Distribution

linux ubuntu 20.04

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
在评估组件中，源码如下：elif isinstance(model, LGBMClassifier):
        predict_data = df[model.origin_feature_name_]
        predict_result = pandas.DataFrame(
            [round(x, 6) for x in model.predict_proba(predict_data)[:, 1]],
            columns=[task_config[PRED_NAME]],
        )
    elif isinstance(model, LGBMRegressor):
        predict_data = df[model.origin_feature_name_]
        predict_result = pandas.DataFrame(
            [round(x, 6) for x in model.predict(predict_data)],
            columns=[task_config[PRED_NAME]],
        )
但实际上model.origin_feature_name_这个属性不存在，应该换用feature_name_这个属性
```

### Reproduction code to reproduce the issue.

```shell
这样使用评估组件会直接报错
```

**Comment by 1853582** [comment]
![image](https://github.com/user-attachments/assets/5f40f92f-ffef-4742-946a-4813a98b59e5)
![image](https://github.com/user-attachments/assets/e0b0546a-3f1b-4a02-9044-83b1af650476)

**Comment by 1853582** [comment]
![image](https://github.com/user-attachments/assets/52b7aa50-0aac-4abe-8f6b-f7f6efc25d9c)
![image](https://github.com/user-attachments/assets/2ed2de98-b05b-48d8-991f-e303ac692176)

**Comment by zhongtianq** [comment]
你好，这个字段是在训练组件中我们添加的。
https://github.com/asterinas/trustflow-teeapps/blob/main/teeapps/biz/lgbm/lgbm.py#L88

确实不是lightgbm中自带的字段，我们这么做的原因是lightgbm中的模型存储是按照空格分割的，无法满足我们一个field中包含空格的情况。
