### ISSUE TITLE
TrustFlow新组件开发是如何编译的

### ISSUE THREAD

**Issue by hallowsman** [secretflow/teeapps#30]
### Issue Type

Build/Install

### Source

source

### Capsule Manager Version

capsule-manager-sim-ubuntu22.04:latest

### Capsule Manager SDK Version

capsule-manager-sim-ubuntu22.04:latest

### Tee Apps Version

0.4.0b0

### OS Platform and Distribution

Ubuntu 22.04 LTS (GNU/Linux 6.5.11-8-pve x86_64)

### Python version

Python 3.10.12

### What happend and What you expected to happen.

```shell
https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/development/new_component
按照文档中的新组件开发文档，

3. 生成新的组件列表(可选)
进入开发容器

bash env.sh
bash env.sh enter

请问上边的进入开发容器是什么意思？怎么进入开发容器？是ubuntu的root环境直接执行代码？还是什么？
直接在ubuntu环境执行会报错如下
root@secretnote-zhaoxiong:/home/trustflow-teeapps# ls -l
total 68
-rw-r--r-- 1 root root   598 Sep 18 10:54 BUILD.bazel
-rw-r--r-- 1 root root   578 Sep 18 10:54 LEGAL.md
-rw-r--r-- 1 root root 11558 Sep 18 10:54 LICENSE
-rw-r--r-- 1 root root 17006 Sep 18 10:54 README.md
-rw-r--r-- 1 root root  1714 Sep 18 10:54 WORKSPACE
drwxr-xr-x 3 root root  4096 Sep 18 10:54 bazel
drwxr-xr-x 6 root root  4096 Sep 18 13:10 deployment
-rw-r--r-- 1 root root  2260 Sep 18 10:54 env.sh
drwxr-xr-x 2 root root  4096 Sep 18 10:54 integration_test
drwxr-xr-x 2 root root  4096 Sep 18 10:54 scripts
drwxr-xr-x 8 root root  4096 Sep 18 10:54 teeapps
root@secretnote-zhaoxiong:/home/trustflow-teeapps# bash env.sh
env.sh: line 17: $'\r': command not found
env.sh: line 21: $'\r': command not found
env.sh: line 24: $'\r': command not found
env.sh: line 27: $'\r': command not found
env.sh: line 30: $'\r': command not found
env.sh: line 32: $'\r': command not found
env.sh: line 34: $'\r': command not found
env.sh: line 39: syntax error near unexpected token `elif'
'nv.sh: line 39: `elif [ -e "$SGX2_ENCLAVE_DEVICE" ] && [ -e "$SGX2_PROVISION_DEVICE" ]; then


构建Teeapps镜像 这个步骤里面
在主机上用deployment目录下的build.sh脚本来构建不同平台下的镜像。
cd deployment

bash build.sh -p sim -v ${VERSION}

bash build.sh -p sgx -v ${VERSION}

bash build.sh -p tdx -v ${VERSION}

bash build.sh -p csv -v ${VERSION}

这些命令是在什么情况下执行的？对这一块不太清楚
```

### Reproduction code to reproduce the issue.

```shell
3. 生成新的组件列表(可选)
进入开发容器


bash env.sh
bash env.sh enter   不知道这里表述的进入开发容器是怎么进入？

4 构建Teeapps镜像
在主机上用deployment目录下的build.sh脚本来构建不同平台下的镜像。
cd deployment

bash build.sh -p sim -v ${VERSION}  这个命令的执行是在什么步骤下，直接在docker容器或者ubuntu环境中执行是报错的，还需要什么其他环境吗？
```

**Comment by zhongtianq** [comment]
env.sh的作用是拉取和进入trustflow-dev镜像（docker镜像），里面安装好了编译环境。可以用bazel编译。主要是开发的时候编译和测试使用。

deployment目录下的脚本会用trustflow-dev镜像编译，然后将产物copy到trustflow-release镜像中，产出对应的release镜像。主要是交付部署的时候使用。

**Comment by zhongtianq** [comment]
对于env.sh出现如你所说的报错：env.sh: line 17: $'\r': command not found。

我猜测你的脚本文件是不是在windows下编辑过导致它的换行符格式等错乱了。直接在ubuntu下执行这个脚本文件本身应该没有问题。

**Comment by hallowsman** [comment]
> env.sh的作用是拉取和进入trustflow-dev镜像（docker镜像），里面安装好了编译环境。可以用bazel编译。主要是开发的时候编译和测试使用。
> 
> deployment目录下的脚本会用trustflow-dev镜像编译，然后将产物copy到trustflow-release镜像中，产出对应的release镜像。主要是交付部署的时候使用。

这个执行了cd deployment

bash build.sh -p sim -v 0.4.0b0以后生成的文件目录是
![image](https://github.com/user-attachments/assets/d60e3d77-7fe5-45ea-862b-47eea8a80dc5)

能不能具体说一下是拷贝哪个文件目录到步骤四中的哪个目录 步骤四进入的是teeapp/sim/teeapps
![image](https://github.com/user-attachments/assets/024597e8-474d-44a5-bc6c-18a23d38cbe8)

**Comment by zhongtianq** [comment]
> > env.sh的作用是拉取和进入trustflow-dev镜像（docker镜像），里面安装好了编译环境。可以用bazel编译。主要是开发的时候编译和测试使用。
> > deployment目录下的脚本会用trustflow-dev镜像编译，然后将产物copy到trustflow-release镜像中，产出对应的release镜像。主要是交付部署的时候使用。
> 
> 这个执行了cd deployment
> 
> bash build.sh -p sim -v 0.4.0b0以后生成的文件目录是 ![image](https://private-user-images.githubusercontent.com/13879625/368534995-d60e3d77-7fe5-45ea-862b-47eea8a80dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgxNzAsIm5iZiI6MTcyNjY1Nzg3MCwicGF0aCI6Ii8xMzg3OTYyNS8zNjg1MzQ5OTUtZDYwZTNkNzctN2ZlNS00NWVhLTg2MmItNDdlZWE4YTgwZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDExMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzQxYmQxOTJhZWZhNDk3Y2FhOGIxMmI3ZGUyYzE3MTI0YWU3ZTNjZGY1YWE3NmMxNWZkYzZhMGIxZjJjMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YOoGURMTtFiY5nXzETmxhgRQ2AraZsVi-HA1SQXcg4o)
> 
> 能不能具体说一下是拷贝哪个文件目录到步骤四中的哪个目录 步骤四进入的是teeapp/sim/teeapps ![image](https://private-user-images.githubusercontent.com/13879625/368535477-024597e8-474d-44a5-bc6c-18a23d38cbe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgxNzAsIm5iZiI6MTcyNjY1Nzg3MCwicGF0aCI6Ii8xMzg3OTYyNS8zNjg1MzU0NzctMDI0NTk3ZTgtNDc0ZC00NGE1LWJjNmMtMThhMjNkMzhjYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDExMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTc1ZWUwMmEyNTYwMGM2MzY5NWZhN2I0ZjMwNDNlODYzYjM5NWJmNTg5MDc0ODVkMzNjYTNkM2Y2YWE0ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5WUps1xnqtu9EEKpED0XBy9GviFHQO3pOU2L2gTMhD8)

```bash
cd deployment
bash build.sh -p sim -v 0.4.0b0
```
这个命令生成的是一个docker镜像，已经把所有东西copy到产物镜像中了，具体操作都可以在脚本中看到，包括使用的dockerfile也在deployment目录下。

如果是想在当前目录看产物，可以用env.sh进入开发镜像后执行：
```bash
bazel --output_base=target build -c opt --copt=-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG //teeapps/...
```

**Comment by yongboy** [comment]
补充一下，编译出来的镜像，如何使用，可参考：
https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/quick_start/step4#id6

其实，文档若是能够给出一个镜像使用最佳实践示范教程最好不过了。
