### ISSUE TITLE
capsule_manager 启动时是需要连网吗？connect hygon cert server

### ISSUE THREAD

**Issue by markzhimm** [secretflow/teeapps#32]
capsule_manager init error: Error { code: InternalErr, details: Some("runified_attestation_generate_auth_report err: \"[Enforce fail at trustflow/attestation/collateral/hygon_collateral.cc:60] ret. Failed    to connect hygon cert server, http ret is null\\nStacktrace:\\n#0 trustflow::attestation::generation::CsvAttestationGenerator::GenerateReport()+0x7f9be3d4c692\\n#1 GenerateAttestationReport+0x7f9be3d4ac4e\   \n#2 trustflow_attestation_rs::generate_attestation_report::h7a4db7994aef8760+0x55e58f69c01a\\n\\0\""), location: Some(ErrorLocation { line: 261, file: "capsule-manager/src/server.rs" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lanyy9527** [comment]
执行的启动命令是什么

**Comment by zhongtianq** [comment]
csv模式下产生远程认证报告需要连接海光的证书服务器。
