### ISSUE TITLE
有关Teeapps对于大内存加密数据解密问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/teeapps#34]
为了保证解密过程的安全，teeapps在运行任务时在内存中对加密数据进行解密，如果出现加密的数据太大，占用的空间远超过运行内存时，这种情况下trustedflow有没有考虑过呢？该如何解决

**Comment by zhongtianq** [comment]
你好。加解密的过程是按block进行的，不存在数据量大了内存占用就高了的情况。

**Comment by oceanqdu** [comment]
感谢解答
